# Generated by Django 4.2.7 on 2026-04-20 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plagiarism_detection.themes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre du thème')),
                ('description', models.TextField(verbose_name='Description du thème')),
                ('mots_cles', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=500, verbose_name='Mots-clés')),
                ('fichier', models.FileField(blank=True, null=True, upload_to=plagiarism_detection.themes.models.theme_file_path, verbose_name='Fichier complémentaire')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_REVUE_CHEF', 'En révision (Chef de département)'), ('EN_REVUE_DA', 'En révision (DA)'), ('VALIDE', 'Validé'), ('REJETE_CHEF', 'Rejeté par le Chef de département'), ('REJETE_DA', 'Rejeté par le DA'), ('REJETE_DEFINITIF', 'Rejeté définitivement')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('valide_par_chef', models.BooleanField(default=False, verbose_name='Validé par le Chef')),
                ('date_validation_chef', models.DateTimeField(blank=True, null=True, verbose_name='Date validation Chef')),
                ('valide_par_da', models.BooleanField(default=False, verbose_name='Validé par le DA')),
                ('date_validation_da', models.DateTimeField(blank=True, null=True, verbose_name='Date validation DA')),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('date_rejet', models.DateTimeField(blank=True, null=True, verbose_name='Date du rejet')),
                ('departement', models.CharField(choices=[('INFORMATIQUE', 'Informatique'), ('MATHEMATIQUES', 'Mathématiques'), ('PHYSIQUE', 'Physique'), ('CHIMIE', 'Chimie'), ('BIOLOGIE', 'Biologie'), ('DROIT', 'Droit'), ('ECONOMIE', 'Économie'), ('MEDECINE', 'Médecine'), ('LETTRES', 'Lettres'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Département')),
                ('est_test_prive', models.BooleanField(default=False, verbose_name='Est un test privé')),
                ('score_similarite', models.FloatField(default=0.0, help_text='Pourcentage de similarité avec les thèmes existants', verbose_name='Score de similarité (%)')),
                ('themes_similaires', models.JSONField(blank=True, default=list, verbose_name='Thèmes similaires trouvés')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='themes', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('rejete_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes_rejetes', to=settings.AUTH_USER_MODEL, verbose_name='Rejeté par')),
            ],
            options={
                'verbose_name': 'Thème',
                'verbose_name_plural': 'Thèmes',
                'ordering': ['-created_at'],
            },
        ),
    ]
