# Generated by Django 4.2.7 on 2026-04-20 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SOUMISSION', 'Soumission'), ('VALIDATION', 'Validation'), ('REJET', 'Rejet'), ('SUPPRESSION', 'Suppression'), ('TEST_PLAGIAT', 'Test de plagiat'), ('TELECHARGEMENT', 'Téléchargement')], max_length=20, verbose_name='Action')),
                ('entity_type', models.CharField(choices=[('REPORT', 'Rapport'), ('THEME', 'Thème'), ('DOCUMENT', 'Document'), ('USER', 'Utilisateur')], max_length=20, verbose_name="Type d'entité")),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name="ID de l'entité")),
                ('details', models.TextField(help_text="Description détaillée de l'action", verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('departement', models.CharField(blank=True, choices=[('INFORMATIQUE', 'Informatique'), ('MATHEMATIQUES', 'Mathématiques'), ('PHYSIQUE', 'Physique'), ('CHIMIE', 'Chimie'), ('BIOLOGIE', 'Biologie'), ('DROIT', 'Droit'), ('ECONOMIE', 'Économie'), ('MEDECINE', 'Médecine'), ('LETTRES', 'Lettres'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Département')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Entrée d'historique",
                'verbose_name_plural': 'Historique',
                'ordering': ['-created_at'],
            },
        ),
    ]
