# Generated by Django 4.2.7 on 2026-04-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='departement',
            field=models.CharField(blank=True, choices=[('MIAGE', 'Méthodes Informatiques Appliquées à la Gestion des Entreprises'), ('ABF', 'Analyse et Pilotage Budgetaire et Financiere'), ('CCA', 'Comptabilite Controle Audit'), ('MID', 'Management et Innovation Digitale'), ('ADB', 'Assurance et Actuariat de Base'), ('ADC', 'Audit et Controle de Gestion'), ('INFORMATIQUE', 'Informatique'), ('MATHEMATIQUES', 'Mathématiques'), ('PHYSIQUE', 'Physique'), ('CHIMIE', 'Chimie'), ('BIOLOGIE', 'Biologie'), ('DROIT', 'Droit'), ('ECONOMIE', 'Économie'), ('MEDECINE', 'Médecine'), ('LETTRES', 'Lettres'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Département'),
        ),
    ]
