# Generated by Django 4.2.7 on 2026-04-20 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NOUVEAU_RAPPORT', 'Nouveau rapport soumis'), ('NOUVEAU_THEME', 'Nouveau thème soumis'), ('RAPPORT_VALIDE', 'Rapport validé'), ('THEME_VALIDE', 'Thème validé'), ('RAPPORT_REJETE', 'Rapport rejeté'), ('THEME_REJETE', 'Thème rejeté'), ('RAPPORT_REJETE_DA', 'Rapport rejeté par le DA'), ('THEME_REJETE_DA', 'Thème rejeté par le DA'), ('RAPPORT_REJETE_DEFINITIF', 'Rapport rejeté définitivement'), ('THEME_REJETE_DEFINITIF', 'Thème rejeté définitivement'), ('RAPPORT_A_VALIDER', 'Rapport à valider'), ('THEME_A_VALIDER', 'Thème à valider'), ('TEST_PLAGIAT_TERMINE', 'Test de plagiat terminé'), ('PLAGIAT_DETECTE', 'Plagiat détecté'), ('SYSTEME', 'Notification système')], max_length=30, verbose_name='Type')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.URLField(blank=True, null=True, verbose_name='Lien')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('email_envoye', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('date_envoi_email', models.DateTimeField(blank=True, null=True, verbose_name='Date envoi email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
