# Generated by Django 4.2.7 on 2026-04-20 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plagiarism_detection.reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre du rapport')),
                ('type_document', models.CharField(choices=[('MEMOIRE', 'Mémoire de Licence'), ('MASTER', 'Mémoire de Master'), ('THESE', 'Thèse de Doctorat'), ('DOCTORAT', 'Doctorat')], default='MEMOIRE', max_length=20, verbose_name='Type de document')),
                ('fichier', models.FileField(help_text='Formats acceptés: PDF, DOCX, TXT', upload_to=plagiarism_detection.reports.models.report_file_path, verbose_name='Fichier du rapport')),
                ('fichier_nom_original', models.CharField(blank=True, max_length=255, verbose_name='Nom original du fichier')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_REVUE_CHEF', 'En révision (Chef de département)'), ('EN_REVUE_DA', 'En révision (DA)'), ('VALIDE', 'Validé'), ('REJETE_CHEF', 'Rejeté par le Chef de département'), ('REJETE_DA', 'Rejeté par le DA'), ('REJETE_DEFINITIF', 'Rejeté définitivement')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('valide_par_chef', models.BooleanField(default=False, verbose_name='Validé par le Chef')),
                ('date_validation_chef', models.DateTimeField(blank=True, null=True, verbose_name='Date validation Chef')),
                ('valide_par_da', models.BooleanField(default=False, verbose_name='Validé par le DA')),
                ('date_validation_da', models.DateTimeField(blank=True, null=True, verbose_name='Date validation DA')),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('date_rejet', models.DateTimeField(blank=True, null=True, verbose_name='Date du rejet')),
                ('pdf_signe', models.FileField(blank=True, null=True, upload_to=plagiarism_detection.reports.models.signed_pdf_path, verbose_name='PDF signé et tamponné')),
                ('departement', models.CharField(choices=[('INFORMATIQUE', 'Informatique'), ('MATHEMATIQUES', 'Mathématiques'), ('PHYSIQUE', 'Physique'), ('CHIMIE', 'Chimie'), ('BIOLOGIE', 'Biologie'), ('DROIT', 'Droit'), ('ECONOMIE', 'Économie'), ('MEDECINE', 'Médecine'), ('LETTRES', 'Lettres'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Département')),
                ('nombre_pages', models.IntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('nombre_mots', models.IntegerField(blank=True, null=True, verbose_name='Nombre de mots')),
                ('score_plagiat_global', models.FloatField(default=0.0, verbose_name='Score de plagiat global (%)')),
                ('est_plagiat', models.BooleanField(default=False, verbose_name='Est considéré comme plagiat')),
                ('est_test_prive', models.BooleanField(default=False, verbose_name='Est un test privé')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('rejete_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_rejetes', to=settings.AUTH_USER_MODEL, verbose_name='Rejeté par')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlagiarismResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_detection', models.CharField(choices=[('PAR_CHAPITRE', 'Détection par chapitre'), ('GLOBAL', 'Détection globale')], default='PAR_CHAPITRE', max_length=20, verbose_name='Type de détection')),
                ('score_global', models.FloatField(verbose_name='Score de plagiat global (%)')),
                ('score_par_chapitre', models.JSONField(blank=True, default=dict, verbose_name='Scores par chapitre')),
                ('similitudes_trouvees', models.JSONField(default=list, help_text='Liste détaillée des similitudes avec sources', verbose_name='Similitudes trouvées')),
                ('date_test', models.DateTimeField(auto_now_add=True, verbose_name='Date du test')),
                ('est_valide', models.BooleanField(default=True, verbose_name='Résultat valide')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents_reference', models.ManyToManyField(blank=True, related_name='plagiarism_results', to='documents.referencedocument', verbose_name='Documents de référence')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_results', to='reports.report', verbose_name='Rapport')),
                ('teste_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Testé par')),
            ],
            options={
                'verbose_name': 'Résultat de Plagiat',
                'verbose_name_plural': 'Résultats de Plagiat',
                'ordering': ['-date_test'],
            },
        ),
        migrations.CreateModel(
            name='ReportChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chapitre', models.IntegerField(verbose_name='Numéro du chapitre')),
                ('titre_chapitre', models.CharField(blank=True, max_length=255, verbose_name='Titre du chapitre')),
                ('contenu', models.TextField(verbose_name='Contenu du chapitre')),
                ('nombre_mots', models.IntegerField(verbose_name='Nombre de mots')),
                ('score_plagiat', models.FloatField(default=0.0, verbose_name='Score de plagiat (%)')),
                ('passages_plagies', models.JSONField(blank=True, default=list, help_text='Liste des passages plagiés avec leurs sources', verbose_name='Passages plagiés détectés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='reports.report', verbose_name='Rapport')),
            ],
            options={
                'verbose_name': 'Chapitre de Rapport',
                'verbose_name_plural': 'Chapitres de Rapports',
                'ordering': ['numero_chapitre'],
                'unique_together': {('report', 'numero_chapitre')},
            },
        ),
    ]
