# Generated by Django 4.2.7 on 2026-04-20 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import plagiarism_detection.accounts.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('role', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('CHEF_DEPARTEMENT', 'Chef de Département'), ('DA', 'Directeur Académique'), ('SECRETAIRE', 'Secrétaire'), ('ADMIN', 'Administrateur')], default='ETUDIANT', max_length=20, verbose_name='Rôle')),
                ('departement', models.CharField(choices=[('INFORMATIQUE', 'Informatique'), ('MATHEMATIQUES', 'Mathématiques'), ('PHYSIQUE', 'Physique'), ('CHIMIE', 'Chimie'), ('BIOLOGIE', 'Biologie'), ('DROIT', 'Droit'), ('ECONOMIE', 'Économie'), ('MEDECINE', 'Médecine'), ('LETTRES', 'Lettres'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Département')),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matricule')),
                ('niveau_etude', models.CharField(blank=True, max_length=50, null=True, verbose_name="Niveau d'étude")),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', plagiarism_detection.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo de profil')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
            },
        ),
    ]
