# Generated by Django 4.2.7 on 2026-04-20 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plagiarism_detection.documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre du document')),
                ('auteur', models.CharField(blank=True, max_length=255, verbose_name='Auteur(s)')),
                ('annee', models.IntegerField(blank=True, null=True, verbose_name='Année de publication')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(help_text='Formats acceptés: PDF, DOCX, TXT', upload_to=plagiarism_detection.documents.models.reference_document_path, verbose_name='Fichier')),
                ('fichier_nom_original', models.CharField(blank=True, max_length=255, verbose_name='Nom original du fichier')),
                ('type_document', models.CharField(choices=[('MEMOIRE', 'Mémoire de Licence'), ('MASTER', 'Mémoire de Master'), ('THESE', 'Thèse de Doctorat'), ('DOCTORAT', 'Doctorat'), ('ARTICLE', 'Article scientifique'), ('RAPPORT', 'Rapport technique'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de document')),
                ('departement', models.CharField(choices=[('INFORMATIQUE', 'Informatique'), ('MATHEMATIQUES', 'Mathématiques'), ('PHYSIQUE', 'Physique'), ('CHIMIE', 'Chimie'), ('BIOLOGIE', 'Biologie'), ('DROIT', 'Droit'), ('ECONOMIE', 'Économie'), ('MEDECINE', 'Médecine'), ('LETTRES', 'Lettres'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Département')),
                ('mots_cles', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=500, verbose_name='Mots-clés')),
                ('nombre_pages', models.IntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('nombre_mots', models.IntegerField(blank=True, null=True, verbose_name='Nombre de mots')),
                ('contenu_extrait', models.TextField(blank=True, help_text='Contenu textuel extrait du document pour la comparaison', verbose_name='Contenu extrait')),
                ('est_actif', models.BooleanField(default=True, help_text='Si False, ce document ne sera pas utilisé pour la comparaison', verbose_name='Actif')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_ajoutes', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name': 'Document de référence',
                'verbose_name_plural': 'Documents de référence',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
